# fly.toml app configuration file generated for barkeepers-handbook-api on 2025-04-28T22:20:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'barkeepers-handbook-api'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
